# -*- coding: utf-8 -*-
"""Kelompok 5_Scrapping Data Twitter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14qLohZDXXcSq95ZifXNmoJEHpITLBxnX
"""

#@title Twitter Auth Token

twitter_auth_token = 'e1d8bde9c4a2e34b598943492bb4f38f8215be11'

# Import required Python package
!pip install pandas

# Install Node.js (because tweet-harvest built using Node.js)
!sudo apt-get update
!sudo apt-get install -y ca-certificates curl gnupg
!sudo mkdir -p /etc/apt/keyrings
!curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg

!NODE_MAJOR=20 && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list

!sudo apt-get update
!sudo apt-get install nodejs -y

!node -v

# Crawl Data
filename = 'isu_starbucks.csv'
search_keyword = 'isu starbucks lang:id'
limit = 100

!npx -yes tweet-harvest@2.6.1 -o "{filename}" -s "{search_keyword}" -l {limit} --token {twitter_auth_token}

import pandas as pd

# Specify the path to your CSV file
file_path = f"tweets-data/{filename}"

# Read the CSV file into a pandas DataFrame
df = pd.read_csv(file_path, delimiter=",")

# Display the DataFrame
display(df)

# Check the length of the DataFrame
num_rows = len(df)
print(f"Jumlah baris dalam dataframe adalah {num_rows}.")

# Cek jumlah data yang didapatkan
num_tweets = len(df)
print(f"Jumlah tweet dalam dataframe adalah {num_tweets}.")